export type Routes = {
  path: string;
  element: JSX.Element;
};
// Generated by https://quicktype.io

export interface Feature {
  id: string;
  name_en: string;
  name_ar: string;
  price_egp: number;
  price_usd: number;
}
